server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_management
    username: root
    password: Keikantswe@7

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

#sevler for uploading/sending  a file
  #servlet:
   # multipart:
    # enabled: true
     # file-size-threshold: 2KB
      #max-file-size: 200MB
      #max-request-size: 215MB