#server:
#  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/chat_Application
    username: postgres
    password: 123456789

  jpa:
     hibernate:
       ddl-auto: update
     show-sql: true

     properties:
       hibernate:
         format_sql: true
       database: postgresql
       database-platform: org.hibernate.dialect.PostgreSQLDialect


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: chat
      auto-offset-reset: earliest

    topic:
      name: chatting
    template:
      default-topic: ${spring.kafka.topic.name}

    #logging:
       # level:
        #  org.springframework.kafka: INFO
         # Geeks.Chat.kafkaService: INFO


# Uncomment and adjust if you need to configure file upload settings
# servlet:
#   multipart:
#     enabled: true
#     file-size-threshold: 2KB
#     max-file-size: 200MB
#     max-request-size: 215MB

# PostgreSQL datasource configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
#spring.datasource.username=postgres
#spring.datasource.password=123456789
#spring.datasource.driver-class-name=org.postgresql.Driver
  
  # Hibernate properties
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true