server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chat_management
    username: root
    password: 123456789

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: chat
      auto-offset-reset: earliest

    topic:
      name: chatting
    template:
      default-topic: ${spring.kafka.topic.name}

    #logging:
       # level:
        #  org.springframework.kafka: INFO
         # Geeks.Chat.kafkaService: INFO


# Uncomment and adjust if you need to configure file upload settings
# servlet:
#   multipart:
#     enabled: true
#     file-size-threshold: 2KB
#     max-file-size: 200MB
#     max-request-size: 215MB
